import { Head, useForm } from '@/runtime';
import AdminLayout from '../../../layouts/AdminLayout';

type Admission = { id: number; student_name: string; guardian_name: string; telephone: string; desired_program?: string; status: string; created_at: string };
type General = { id: number; full_name: string; telephone: string; subject?: string; status: string; created_at: string };
type Paginator<T> = { data: T[] };
export default function EnquiriesIndex({ admissionEnquiries, generalEnquiries }: { admissionEnquiries: Paginator<Admission>; generalEnquiries: Paginator<General> }) { return <AdminLayout><Head title="Enquiries" /><header className="admin-page-header"><div><span className="admin-kicker">Communication</span><h1>Enquiries</h1><p>Review admission interest and general messages from the public website.</p></div></header><div className="admin-panel full-panel"><div className="admin-panel-heading"><h2>Admission enquiries</h2><span>{admissionEnquiries.data.length} records</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Student</th><th>Guardian</th><th>Program</th><th>Contact</th><th>Status</th><th>Received</th></tr></thead><tbody>{admissionEnquiries.data.map((enquiry) => <AdmissionRow enquiry={enquiry} key={enquiry.id} />)}</tbody></table></div></div><div className="admin-panel full-panel"><div className="admin-panel-heading"><h2>General enquiries</h2><span>{generalEnquiries.data.length} records</span></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Name</th><th>Subject</th><th>Contact</th><th>Status</th><th>Received</th></tr></thead><tbody>{generalEnquiries.data.map((enquiry) => <GeneralRow enquiry={enquiry} key={enquiry.id} />)}</tbody></table></div></div></AdminLayout>; }

function AdmissionRow({ enquiry }: { enquiry: Admission }) { const form = useForm({ status: enquiry.status, internal_notes: '' }); return <tr><td><strong>{enquiry.student_name}</strong></td><td>{enquiry.guardian_name}</td><td>{enquiry.desired_program}</td><td><a href={`tel:${enquiry.telephone}`}>{enquiry.telephone}</a></td><td><form className="inline-form" onSubmit={(event) => { event.preventDefault(); form.patch(`/admin/enquiries/admission/${enquiry.id}`, { preserveScroll: true }); }}><select value={form.data.status} onChange={(event) => form.setData('status', event.target.value)}><option>new</option><option>contacted</option><option>follow-up required</option><option>visit scheduled</option><option>application started</option><option>admitted</option><option>closed</option></select><button type="submit">Save</button></form></td><td>{new Date(enquiry.created_at).toLocaleDateString()}</td></tr>; }
function GeneralRow({ enquiry }: { enquiry: General }) { const form = useForm({ status: enquiry.status }); return <tr><td><strong>{enquiry.full_name}</strong></td><td>{enquiry.subject}</td><td><a href={`tel:${enquiry.telephone}`}>{enquiry.telephone}</a></td><td><form className="inline-form" onSubmit={(event) => { event.preventDefault(); form.patch(`/admin/enquiries/general/${enquiry.id}`, { preserveScroll: true }); }}><select value={form.data.status} onChange={(event) => form.setData('status', event.target.value)}><option>new</option><option>read</option><option>replied</option><option>follow-up required</option><option>closed</option><option>spam</option></select><button type="submit">Save</button></form></td><td>{new Date(enquiry.created_at).toLocaleDateString()}</td></tr>; }
